http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  pets:
    host: 54.147.179.0
    methods: ['GET', 'POST','PUT','DELETE']
    paths: ['/api/pets/','/api/pets/*']
  api:
    host: localhost
    paths: '/ip'
  requests:
    host: 54.147.179.0
    methods: ['GET', 'POST','PUT','DELETE']
    paths: ['/api/requests/*','/api/requests/']
  owners:
    host: 3.17.118.106
    methods: ['GET', 'POST','PUT','DELETE']
    paths: ['/api/owners/*','/api/owners/']
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  petsService:
    url: 'http://34.194.231.115'
  requestsService:
    url: 'http://52.2.159.146'
  ownersService:
    url: 'http://3.17.118.106'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  petsPipelines:
    apiEndpoints:
      - pets
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: petsService 
              changeOrigin: true
  requestsPipelines:
    apiEndpoints:
      - requests
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: requestsService 
              changeOrigin: true
  ownersPipelines:
    apiEndpoints:
      - owners
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: ownersService 
              changeOrigin: true