http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  pets:
    host: localhost
    paths: ["/pets","pets/*"]
  requests:
    host: localhost
    paths: ["/requests","requests/*"]
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  petsServices:
    url: 'http://localhost:3000'    #aqui ip del servicio
  requestsServices:
    url: 'http://localhost:3001'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true

  petsPipeline:
    apiEndpoints:
      - users
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: petsServices 
              changeOrigin: true

  requestsPipeline:
    apiEndpoints:
      - events
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: requestsServices 
              changeOrigin: true