http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  api:
    host: localhost
    paths: '/ip'
  pets:
    host: 54.147.179.0
    methods: ["GET","POST","PUT","DELETE"]
    paths: ["/api/pets","/api/pets/*"]
  requests:
    host: 54.147.179.0
    methods: ["GET","POST","PUT","DELETE"]
    paths: ["/api/requests","/api/requests/*"]

serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  petsServices:
    url: 'http://34.194.231.115'    #aqui ip del servicio
  requestsServices:
    url: 'http://52.2.159.146'
  apiServices:
    url: 'http://54.147.179.0:3001'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true

  apiPipeline:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: apiServices 
              changeOrigin: true

  petsPipeline:
    apiEndpoints:
      - pets
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: petsServices 
              changeOrigin: true

  requestsPipeline:
    apiEndpoints:
      - requests
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: requestsServices 
              changeOrigin: true