http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  pets:
    host: 18.223.193.37
    methods: ['GET', 'POST','PUT','DELETE']
    paths: ['/api/pets/','/api/pets/*']
  api:
    host: localhost
    paths: '/ip'
  requests:
    host: 18.223.193.37
    methods: ['GET', 'POST','PUT','DELETE']
    paths: ['/api/requests/*','/api/requests/']
  owners:
    host: 18.223.193.37
    methods: ['GET', 'POST','PUT','DELETE']
    paths: ['/api/owners/*','/api/owners/']
  pays:
    host: 18.223.193.37
    methods: ['GET', 'POST','PUT']
    paths: ['/api/pays/*','/api/pays/']
serviceEndpoints:
  httpbin:
    url: 'https://httpbin.org'
  petsService:
    url: 'http://3.145.144.79'
  requestsService:
    url: 'http://3.138.140.247'
  ownersService:
    url: 'http://3.145.198.108'
  paysService:
    url: 'http://18.191.19.83'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin 
              changeOrigin: true
  petsPipelines:
    apiEndpoints:
      - pets
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: petsService 
              changeOrigin: true
  requestsPipelines:
    apiEndpoints:
      - requests
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: requestsService 
              changeOrigin: true
  ownersPipelines:
    apiEndpoints:
      - owners
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: ownersService 
              changeOrigin: true
  paysPipelines:
    apiEndpoints:
      - pays
    policies:
    # Uncomment `key-auth:` when instructed to in the Getting Started guide.
    # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: paysService 
              changeOrigin: true